spring:
  cloud:
    gateway:
      routes:
        # MANAGEMENT INTEGRATIONS
        - id: managementintegrations_route--get-list-by-managementId
          uri: ${configs.api.managements.integrations.baseUrl}
          predicates:
            - Path=/management/integrations/project-management/{projectManagementId}/**
            - Method=GET
          filters:
            - RewritePath=/${configs.api.managements.integrations.inManagementBasedPath}(?<segment>.*), /${configs.api.managements.integrations.outManagementBasedPath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - ValidateIsAdmin=GET,true,projectManagement
            - AddIsAdminHeader
            - SetRequestHeader=Content-Type, application/prs.hal-forms+json
            - TokenRelay
        - id: managementintegrations_route--post-by-managementId
          uri: ${configs.api.managements.integrations.baseUrl}
          predicates:
            - Path=/management/integrations/project-management/{projectManagementId}/**
            - Method=POST
          filters:
            - RewritePath=/${configs.api.managements.integrations.inManagementBasedPath}(?<segment>.*), /${configs.api.managements.integrations.outManagementBasedPath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - ValidateIsAdmin=managementId,false,projectManagement
            - AddIsAdminHeader
            - SetRequestHeader=Content-Type, application/prs.hal-forms+json
            - TokenRelay
        - id: managementintegrations_route--post
          uri: ${configs.api.managements.integrations.baseUrl}
          predicates:
            - Path=/management/integrations/**
            - Method=POST
          filters:
            - RewritePath=/${configs.api.managements.integrations.inBasePath}(?<segment>.*), /${configs.api.managements.integrations.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - TokenRelay=
        - id: managementintegrations_route--patch
          uri: ${configs.api.managements.integrations.baseUrl}
          predicates:
            - Path=/management/integrations/**
            - Method=PATCH
          filters:
            - RewritePath=/${configs.api.managements.integrations.inBasePath}(?<segment>.*), /${configs.api.managements.integrations.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - TokenRelay=
        - id: managementintegrations_route--get-by-id
          uri: ${configs.api.managements.integrations.baseUrl}
          predicates:
            - Path=/management/integrations/**
            - Method=GET
          filters:
            - RewritePath=/${configs.api.managements.integrations.inBasePath}(?<segment>.*), /${configs.api.managements.integrations.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - TokenRelay=
        # CLUBS
        #        - id: clubs_route--get-wellknown-club
        #          uri: ${configs.api.clubs.baseUrl}
        #          predicates:
        #            - Path=/clubs/well-known/{projectId}/{clubType}
        #            - Method=GET
        #          filters:
        #            - RewritePath=/${configs.api.clubs.inBasePath}(?<segment>.*), /${configs.api.clubs.outBasePath}$\{segment}
        #            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
        #            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
        #            - TokenRelay=
        - id: clubs_route--get-all-wellknown-club
          uri: ${configs.api.clubs.baseUrl}
          predicates:
            - Path=/clubs/well-known/{projectId}
            - Method=GET
          filters:
            - SetRequestHeader=Content-Type, application/prs.hal-forms+json # not necessary?
            - RewritePath=/${configs.api.clubs.inBasePath}(?<segment>.*), /${configs.api.clubs.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false},${configs.api.projects.core.baseUrl}
            - ValidateIsAdmin=GET,true
            - AddIsAdminHeader
            - TokenRelay
        - id: clubs_route--get-administered-wellknown-club
          uri: ${configs.api.clubs.baseUrl}
          predicates:
            - Path=/clubs/well-known
            - Method=GET
          filters:
            - RewritePath=/${configs.api.clubs.inBasePath}(?<segment>.*), /${configs.api.clubs.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - TokenRelay=
        - id: clubs_route--patch-wellknown-club
          uri: ${configs.api.clubs.baseUrl}
          predicates:
            - Path=/clubs/well-known/{projectId}/{type}
            - Method=PATCH
          filters:
            - RewritePath=/${configs.api.clubs.inBasePath}(?<segment>.*), /${configs.api.clubs.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false},${configs.api.events.baseUrl}
            - A6EventPrepare
            - name: A6EventTrigger
              args:
                subjectType: club
                subjectIdUriTemplateKeys: projectId+type
                defaultSubjectEvent: modifyMember
                patchToSubjectEventMap:
                  members:
                    remove: removeMember
                    add: addMember
            - TokenRelay=
        - id: clubs_route--register-wellknown-clubs
          uri: ${configs.api.clubs.baseUrl}
          predicates:
            - Path=/clubs/well-known/{projectId}
            - Method=POST
          filters:
            - SetRequestHeader=Content-Type, application/prs.hal-forms+json
            - RewritePath=/${configs.api.clubs.inBasePath}(?<segment>.*), /${configs.api.clubs.outBasePath}$\{segment}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - AddGoogleCloudRunAuthHeader=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false}
            - ProcessGoogleCloudRunAuth=${A6_GATEWAY_INFRA_GOOGLE_CLOUDRUN_AUTH_ENABLED:false},${configs.api.projects.core.baseUrl}
            - ValidateIsAdmin
            - AddIsAdminHeader
            - TokenRelay