server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://127.0.0.1:8761/eureka/}
      

