server:
  port: ${A6_GATEWAY_PORT:10000}

logging:
  level:
    "[org.springframework.cloud.gateway]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.http.server.reactive]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.web.reactive]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.boot.autoconfigure.web]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[reactor.netty]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.security]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[com.angorasix]": ${A6_GATEWAY_LOGGING_LEVEL_ANGORASIX:INFO}

configs:
  api:
    contributors:
      baseUrl: ${A6_GATEWAY_CONTRIBUTORS_URI:http://localhost:10100}
      inBasePath: ${A6_GATEWAY_CONTRIBUTORS_INBASEPATH:contributors}
      outBasePath: ${A6_GATEWAY_CONTRIBUTORS_OUTBASEPATH:contributors}
    projects:
      core:
        baseUrl: ${A6_GATEWAY_PROJECTS_CORE_URI:http://localhost:10200}
        inBasePath: ${A6_GATEWAY_PROJECTS_CORE_INBASEPATH:projects/core}
        outBasePath: ${A6_GATEWAY_PROJECTS_CORE_OUTBASEPATH:projects-core}
      presentation:
        baseUrl: ${A6_GATEWAY_PROJECTS_PRESENTATION_URI:http://localhost:10201}
        inBasePath: ${A6_GATEWAY_PROJECTS_PRESENTATION_INBASEPATH:projects/presentations}
        inProjectBasedPath: ${A6_GATEWAY_PROJECTS_PRESENTATION_INPROJECTBASEDPATH:projects/(?<projectId>.*?)/presentations}
        outBasePath: ${A6_GATEWAY_PROJECTS_PRESENTATION_OUTBASEPATH:projects-presentation}
    managements:
      core:
        baseUrl: ${A6_GATEWAY_PROJECTS_MANAGEMENT_URI:http://localhost:10300}
        inBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INBASEPATH:projects/management}
        outBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_OUTBASEPATH:managements-core}
        inProjectBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INPROJECTBASEDPATH:projects/(?<projectId>.*?)/management}
        outProjectBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_OUTPROJECTBASEDPATH:managements-core/project/$\{projectId}}
      integrations:
        baseUrl: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INTEGRATION_URI:http://localhost:10302}
        inBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INTEGRATION_INBASEPATH:management/integrations}
        inManagementBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INTEGRATION_INMANAGEMENTBASEDPATH:management/integrations/project-management/(?<projectManagementId>.*?)}
        outManagementBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INTEGRATION_OUTMANAGEMENTBASEDPATH:managements-integration/project-management/$\{projectManagementId}}
        outBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INTEGRATION_OUTBASEPATH:managements-integration}
      tasks:
        baseUrl: ${A6_GATEWAY_PROJECTS_MANAGEMENT_TASK_URI:http://localhost:10301}
        inBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_TASK_INBASEPATH:management/tasks}
        inManagementBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_TASK_INMANAGEMENTBASEDPATH:management/tasks/project-management/(?<projectManagementId>.*?)}
        outManagementBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_TASK_OUTMANAGEMENTBASEDPATH:management-tasks/project-management/$\{projectManagementId}}
        outBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_TASK_OUTBASEPATH:management-tasks}
      accounting:
        baseUrl: ${A6_GATEWAY_PROJECTS_MANAGEMENT_ACCOUNTING_URI:http://localhost:10303}
        inBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_ACCOUNTING_INBASEPATH:management/accounting}
        inManagementBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_ACCOUNTING_INMANAGEMENTBASEDPATH:management/accounting/project-management/(?<projectManagementId>.*?)}
        outManagementBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_ACCOUNTING_OUTMANAGEMENTBASEDPATH:management-accounting/project-management/$\{projectManagementId}}
        outBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_ACCOUNTING_OUTBASEPATH:management-accounting}

    media:
      baseUrl: ${A6_GATEWAY_MEDIA_URI:http://localhost:10001}
      inBasePath: ${A6_GATEWAY_MEDIA_INBASEPATH:media}
      outBasePath: ${A6_GATEWAY_MEDIA_OUTBASEPATH:}
    clubs:
      baseUrl: ${A6_GATEWAY_CLUBS_URI:http://localhost:10900}
      inBasePath: ${A6_GATEWAY_CLUBS_INBASEPATH:clubs}
      outBasePath: ${A6_GATEWAY_CLUBS_OUTBASEPATH:clubs}
      inProjectBasedPath: ${A6_GATEWAY_CLUBS_INPROJECTBASEDPATH:clubs/project/(?<projectId>.*?)}
      outProjectBasedPath: ${A6_GATEWAY_CLUBS_OUTPROJECTBASEDPATH:clubs/project/$\{projectId}}
      inManagementBasedPath: ${A6_GATEWAY_CLUBS_INMANAGEMENTBASEDPATH:clubs/project-management/(?<projectManagementId>.*?)}
      outManagementBasedPath: ${A6_GATEWAY_CLUBS_OUTMANAGEMENTBASEDPATH:clubs/project-management/$\{projectManagementId}}
    events:
      baseUrl: ${A6_GATEWAY_EVENTS_URI:http://localhost:10101}
      inBasePath: ${A6_GATEWAY_EVENTS_INBASEPATH:events}
      outBasePath: ${A6_GATEWAY_EVENTS_OUTBASEPATH:events}
    notifications:
      baseUrl: ${A6_GATEWAY_NOTIFICATIONS_URI:http://localhost:10102}
      inBasePath: ${A6_GATEWAY_NOTIFICATIONS_INBASEPATH:notifications}
      outBasePath: ${A6_GATEWAY_NOTIFICATIONS_OUTBASEPATH:notifications}
    surveys:
      baseUrl: ${A6_GATEWAY_SURVEYS_URI:http://localhost:10951}
      inBasePath: ${A6_GATEWAY_SURVEYS_INBASEPATH:surveys}
      outBasePath: ${A6_GATEWAY_SURVEYS_OUTBASEPATH:surveys}
  internalRoutes:
    projectsCore:
      isAdminEndpoint: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCORE_ISADMIN::projectId/isAdmin}
      projectsEndpoint: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCORE_PROJECTS:}
    managementsCore:
      isAdminEndpoint: ${A6_GATEWAY_INTERNALROUTES_MANAGEMENTSCORE_ISADMIN::projectManagementId/isAdmin}
    projectsCoreParams:
      adminIdQueryParam: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_ADMINIDQUERYPARAM:adminId}
      projectIdResponseField: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_PROJECTIDRESPONSEFIELD:id}
      projectIdQueryParam: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_PROJECTIDQUERYPARAM:projectId}
    events:
      publishA6Event: ${A6_GATEWAY_INTERNALROUTES_EVENTS_A6_RESOURCE:a6-resource}
  constants:
    projectIdParam: projectId
    mgmtIdParam: projectManagementId
    mgmtIdPlaceholder: :projectManagementId
    projectIdPlaceholder: :projectId
    adminProjectIdsParam: adminProjectIds
    isAdminAttribute: com.angorasix.gateway.infrastructure.config.constants.isProjectAdmin
    projectIdsAttribute: com.angorasix.gateway.infrastructure.config.constants.projectIds
    googleTokenAttribute: com.angorasix.gateway.infrastructure.config.constants.googleCloudRunIdToken
    googleTokenUrlPattern: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=:audience
    googleAudiencePlaceholder: :audience

spring:
  config:
    import:
      - optional:file:config/env.properties
      - classpath:/security.yml
      - classpath:routes/clubs.yml
      - classpath:routes/contributors.yml
      - classpath:routes/management-integrations.yml
      - classpath:routes/management-tasks.yml
      - classpath:routes/management-accounting.yml
      - classpath:routes/media.yml
      - classpath:routes/notifications.yml
      - classpath:routes/projects-core.yml
      - classpath:routes/projects-management.yml
      - classpath:routes/projects-presentation.yml
      - classpath:routes/surveys.yml
  application:
    name: ${APP_NAME:gateway}
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${A6_GATEWAY_CORS_ALLOWEDORIGINS:}
            allowedMethods:
              - GET
      #      httpclient:
      #        wiretap:true
      #      httpserver:
      #        wiretap: true