server:
  port: ${A6_GATEWAY_PORT:9080}

logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        #        web:
        #          reactive: DEBUG
        #        http:
        #          server:
        #            reactive: DEBUG
        cloud:
          gateway: DEBUG

configs:
  api:
    common:
      contributorHeader: ${A6_GATEWAY_COMMON_CONTRIBUTORHEADER:A6-Contributor}
    contributors:
      baseURL: ${A6_GATEWAY_CONTRIBUTORS_URI:http://localhost:9081}
      inBasePath: ${A6_GATEWAY_CONTRIBUTORS_INBASEPATH:contributors}
      outBasePath: ${A6_GATEWAY_CONTRIBUTORS_OUTBASEPATH:auth/admin/realms/Angorasix/users}
    projects:
      core:
        baseURL: ${A6_GATEWAY_PROJECTS_CORE_URI:http://localhost:9082}
        inBasePath: ${A6_GATEWAY_PROJECTS_CORE_INBASEPATH:projects/core}
        outBasePath: ${A6_GATEWAY_PROJECTS_CORE_OUTBASEPATH:projects-core}
      presentation:
        baseURL: ${A6_GATEWAY_PROJECTS_PRESENTATION_URI:http://localhost:9083}
        inBasePath: ${A6_GATEWAY_PROJECTS_PRESENTATION_INBASEPATH:projects/presentations}
        inProjectBasedPath: ${A6_GATEWAY_PROJECTS_PRESENTATION_INPROJECTBASEDPATH:projects/(?<projectId>.*?)/presentations}
        outBasePath: ${A6_GATEWAY_PROJECTS_PRESENTATION_OUTBASEPATH:projects-presentation}
      management:
        baseURL: ${A6_GATEWAY_PROJECTS_MANAGEMENT_URI:http://localhost:9086}
        inBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INBASEPATH:projects/management}
        inProjectBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INPROJECTBASEDPATH:projects/(?<projectId>.*?)/management}
        outBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_OUTBASEPATH:management-core}
    media:
      baseURL: ${A6_GATEWAY_MEDIA_URI:http://localhost:9084}
      inBasePath: ${A6_GATEWAY_MEDIA_INBASEPATH:media}
      outBasePath: ${A6_GATEWAY_MEDIA_OUTBASEPATH:}
    clubs:
      baseURL: ${A6_GATEWAY_CLUBS_URI:http://localhost:9085}
      inBasePath: ${A6_GATEWAY_CLUBS_INBASEPATH:clubs}
      outBasePath: ${A6_GATEWAY_CLUBS_OUTBASEPATH:clubs}
  internalRoutes:
    projectsCore:
      isAdminEndpoint: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCORE_ISADMIN::projectId/isAdmin}
      projectsEndpoint: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCORE_PROJECTS:}
    projectsCoreParams:
      adminIdQueryParam: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_ADMINIDQUERYPARAM:adminId}
      isAdminResponseField: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_ISADMINRESPONSEFIELD:isAdmin}
      projectIdResponseField: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_PROJECTIDRESPONSEFIELD:id}
      projectIdQueryParam: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_PROJECTIDQUERYPARAM:projectId}
  constants:
    projectIdParam: projectId
    projectIdPlaceholder: :projectId
    adminProjectIdsParam: adminProjectIds
    isProjectAdminAttribute: org.a6.gateway.infrastructure.config.constants.isProjectAdmin
    projectIdsAttribute: org.a6.gateway.infrastructure.config.constants.projectIds

spring:
  config:
    import: file:env.properties,classpath:/routes.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${GATEWAY_SERVICE_OAUTH_SECURITY_ISSUER_URI:http://localhost:9081/auth/realms/Angorasix}
      client:
        registration:
          contributors:
            client-id: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_CLIENT_ID:contributorsClientId}
            client-secret: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_CLIENT_SECRET:contributorsSecret}
            authorization-grant-type: client_credentials
            scope:
        provider:
          contributors:
            token-uri: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_TOKEN_URI:http://localhost:9081/auth/realms/Angorasix/protocol/openid-connect/token}
  application:
    name: ${APP_NAME:gateway}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${GATEWAY_SERVICE_CORS_ALLOWEDORIGINS:http://localhost:90}
            allowedMethods:
              - GET
      #      httpclient:
      #        wiretap:true
      #      httpserver:
      #        wiretap: true