server:
  port: ${A6_GATEWAY_PORT:9080}

logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        #        web:
        #          reactive: DEBUG
        #        http:
        #          server:
        #            reactive: DEBUG
        cloud:
          gateway: DEBUG

configs:
  api:
    contributors:
      baseURL: ${A6_GATEWAY_CONTRIBUTORS_URI:http://localhost:9081}
      adminClientSecret: ${A6_GATEWAY_CONTRIBUTORS_ADMIN_SECRET:secret}
    projects:
      coreBaseURL: ${A6_GATEWAY_PROJECTS_CORE_URI:http://localhost:9082}
      presentationBaseURL: ${A6_GATEWAY_PROJECTS_PRESENTATION_URI:http://localhost:9083}
  auth:
    contributors:
      authKsPass: ${A6_GATEWAY_CONTRIBUTORS_AUTH_KS_SECRET:ksSecret}
      authKsAlias: ${A6_GATEWAY_CONTRIBUTORS_AUTH_KS_ALIAS:ksAlias}

spring:
  config:
    import: file:env.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${GATEWAY_SERVICE_OAUTH_SECURITY_ISSUER_URI:http://localhost:9081/auth/realms/Angorasix}
      client:
        registration:
          contributors:
            client-id: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_CLIENT_ID:contributorsClientId}
            client-authentication-method: private_key_jwt
            authorization-grant-type: client_credentials
            scope:
        provider:
          contributors:
            token-uri: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_TOKEN_URI:http://localhost:9081/auth/realms/Angorasix/protocol/openid-connect/token}
  application:
    name: ${APP_NAME:gateway}
  cloud:
    gateway:
      #      httpclient:
      #        wiretap:true
      #      httpserver:
      #        wiretap: true
      routes:
        - id: contributors_route
          uri: ${configs.api.contributors.baseURL}
          predicates:
            - Path=/contributors/**
          filters:
            - RewritePath=/(?<segment>.*), /auth/realms/Angorasix/protocol/openid-connect/$\{segment}
            - ContributorsAdminRequest
        - id: projectspresentation_route
          uri: ${configs.api.projects.presentationBaseURL}
          predicates:
            - Path=/projects/presentations/**
          filters:
            - RewritePath=/projects/presentations(?<segment>.*), /projects-presentation$\{segment}

