server:
  port: ${A6_GATEWAY_PORT:9080}

logging:
  level:
    "[org.springframework.cloud.gateway]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.http.server.reactive]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.web.reactive]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.boot.autoconfigure.web]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[reactor.netty]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[org.springframework.security]": ${A6_GATEWAY_LOGGING_LEVEL_GATEWAY:INFO}
    "[com.angorasix]": ${A6_GATEWAY_LOGGING_LEVEL_ANGORASIX:INFO}

configs:
  api:
    contributors:
      baseUrl: ${A6_GATEWAY_CONTRIBUTORS_URI:http://localhost:9081}
      inBasePath: ${A6_GATEWAY_CONTRIBUTORS_INBASEPATH:contributors}
      outBasePath: ${A6_GATEWAY_CONTRIBUTORS_OUTBASEPATH:contributors}
    projects:
      core:
        baseUrl: ${A6_GATEWAY_PROJECTS_CORE_URI:http://localhost:9082}
        inBasePath: ${A6_GATEWAY_PROJECTS_CORE_INBASEPATH:projects/core}
        outBasePath: ${A6_GATEWAY_PROJECTS_CORE_OUTBASEPATH:projects-core}
      presentation:
        baseUrl: ${A6_GATEWAY_PROJECTS_PRESENTATION_URI:http://localhost:9083}
        inBasePath: ${A6_GATEWAY_PROJECTS_PRESENTATION_INBASEPATH:projects/presentations}
        inProjectBasedPath: ${A6_GATEWAY_PROJECTS_PRESENTATION_INPROJECTBASEDPATH:projects/(?<projectId>.*?)/presentations}
        outBasePath: ${A6_GATEWAY_PROJECTS_PRESENTATION_OUTBASEPATH:projects-presentation}
      management:
        baseUrl: ${A6_GATEWAY_PROJECTS_MANAGEMENT_URI:http://localhost:9086}
        inBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INBASEPATH:projects/management}
        inProjectBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_INPROJECTBASEDPATH:projects/(?<projectId>.*?)/management}
        outProjectBasedPath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_OUTPROJECTBASEDPATH:management-core/project/$\{projectId}}
        outBasePath: ${A6_GATEWAY_PROJECTS_MANAGEMENT_OUTBASEPATH:management-core}
    media:
      baseUrl: ${A6_GATEWAY_MEDIA_URI:http://localhost:9084}
      inBasePath: ${A6_GATEWAY_MEDIA_INBASEPATH:media}
      outBasePath: ${A6_GATEWAY_MEDIA_OUTBASEPATH:}
    clubs:
      baseUrl: ${A6_GATEWAY_CLUBS_URI:http://localhost:9085}
      inBasePath: ${A6_GATEWAY_CLUBS_INBASEPATH:clubs}
      outBasePath: ${A6_GATEWAY_CLUBS_OUTBASEPATH:clubs}
    events:
      baseUrl: ${A6_GATEWAY_EVENTS_URI:http://localhost:9087}
      inBasePath: ${A6_GATEWAY_EVENTS_INBASEPATH:events}
      outBasePath: ${A6_GATEWAY_EVENTS_OUTBASEPATH:events}
  internalRoutes:
    projectsCore:
      isAdminEndpoint: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCORE_ISADMIN::projectId/isAdmin}
      projectsEndpoint: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCORE_PROJECTS:}
    projectsCoreParams:
      adminIdQueryParam: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_ADMINIDQUERYPARAM:adminId}
      isAdminResponseField: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_ISADMINRESPONSEFIELD:isAdmin}
      projectIdResponseField: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_PROJECTIDRESPONSEFIELD:id}
      projectIdQueryParam: ${A6_GATEWAY_INTERNALROUTES_PROJECTSCOREPARAMS_PROJECTIDQUERYPARAM:projectId}
    events:
      publishA6Event: ${A6_GATEWAY_INTERNALROUTES_EVENTS_A6_RESOURCE:a6-resource}
  constants:
    projectIdParam: projectId
    projectIdPlaceholder: :projectId
    adminProjectIdsParam: adminProjectIds
    isProjectAdminAttribute: org.a6.gateway.infrastructure.config.constants.isProjectAdmin
    projectIdsAttribute: org.a6.gateway.infrastructure.config.constants.projectIds
    googleTokenAttribute: org.a6.gateway.infrastructure.config.constants.googleCloudRunIdToken
    googleTokenUrlPattern: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=:audience
    googleAudiencePlaceholder: :audience

spring:
  config:
    import: optional:file:config/env.properties, optional:file:/config/env.properties, classpath:/routes.yml, , classpath:/security.yml
  application:
    name: ${APP_NAME:gateway}
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${A6_GATEWAY_CORS_ALLOWEDORIGINS:}
            allowedMethods:
              - GET
      #      httpclient:
      #        wiretap:true
      #      httpserver:
      #        wiretap: true