server:
  port: ${A6_GATEWAY_PORT:9080}

logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        #        web:
        #          reactive: DEBUG
        #        http:
        #          server:
        #            reactive: DEBUG
        cloud:
          gateway: DEBUG

configs:
  api:
    contributors:
      baseURL: ${A6_GATEWAY_CONTRIBUTORS_URI:http://localhost:9081}
    projects:
      coreBaseURL: ${A6_GATEWAY_PROJECTS_CORE_URI:http://localhost:9082}
      presentationBaseURL: ${A6_GATEWAY_PROJECTS_PRESENTATION_URI:http://localhost:9083}

spring:
  config:
    import: optional:file:env.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${GATEWAY_SERVICE_OAUTH_SECURITY_ISSUER_URI:http://localhost:9081/auth/realms/Angorasix}
      client:
        registration:
          contributors:
            client-id: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_CLIENT_ID:contributorsClientId}
            client-secret: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_CLIENT_SECRET:contributorsSecret}
            authorization-grant-type: client_credentials
            scope:
        provider:
          contributors:
            token-uri: ${GATEWAY_SERVICE_OAUTH_CONTRIBUTORS_TOKEN_URI:http://localhost:9081/auth/realms/Angorasix/protocol/openid-connect/token}
  application:
    name: ${APP_NAME:gateway}
  cloud:
    gateway:
      #      httpclient:
      #        wiretap:true
      #      httpserver:
      #        wiretap: true
      routes:
        - id: contributors_route
          uri: ${configs.api.contributors.baseURL}
          predicates:
            - Path=/contributors/**
          filters:
            - RewritePath=/(?<segment>.*), /auth/realms/Angorasix/protocol/openid-connect/$\{segment}
            - ContributorsAdminRequest
            - UserScopedRequest
        - id: projectspresentation_route
          uri: ${configs.api.projects.presentationBaseURL}
          predicates:
            - Path=/projects/presentations/**
          filters:
            - RewritePath=/projects/presentations(?<segment>.*), /projects-presentation$\{segment}

