spring:
  cloud:
    gateway:
      routes:
        #  CONTRIBUTORS
        - id: contributors_add_attribute_route
          uri: ${configs.api.contributors.baseURL}
          predicates:
            - Path=/contributors/attributes
            - Method=POST
          filters:
            - RewritePath=/contributors(?<segment>.*), /auth/admin/realms/Angorasix/users/:userId
            - ModifyMethod=PUT
            - ContributorsAdminRequest
            - UserScopedRequest
        - id: contributors_get_contributor
          uri: http://localhost:9081
          predicates:
            - Path=/contributors/{contributorId}
            - Method=GET
          filters:
            - RewritePath=/contributors/(?<segment>.*), /auth/admin/realms/Angorasix/users/$\{segment}
            - ContributorsAdminRequest
        # PROJECTS CORE
        - id: projectscore_route--get--shallow
          uri: ${configs.api.projects.coreBaseURL}
          predicates:
            - Path=/projects/core/**
            - Method=GET
            - Query=shallow
          filters:
            - RewritePath=/projects/core(?<segment>.*), /projects-core$\{segment}
        - id: projectscore_route--get
          uri: ${configs.api.projects.coreBaseURL}
          predicates:
            - Path=/projects/core/**
            - Method=GET
          filters:
            - RewritePath=/projects/core(?<segment>.*), /projects-core$\{segment}
            - ComposeFieldApi=id,/projects/presentations,projectIds,shallow,projectId,presentations,list
        - id: projectscore_route
          uri: ${configs.api.projects.coreBaseURL}
          predicates:
            - Path=/projects/core
          filters:
            - RewritePath=/projects/core(?<segment>.*), /projects-core$\{segment}
            - AddContributorHeader
        # PROJECTS PRESENTATION
        - id: projectspresentation_route--get--shallow
          uri: ${configs.api.projects.presentationBaseURL}
          predicates:
            - Path=/projects/presentations/**
            - Method=GET
            - Query=shallow
          filters:
            - RewritePath=/projects/presentations(?<segment>.*), /projects-presentation$\{segment}
        - id: projectspresentation_route--get
          uri: ${configs.api.projects.presentationBaseURL}
          predicates:
            - Path=/projects/presentations/**
            - Method=GET
          filters:
            - RewritePath=/projects/presentations(?<segment>.*), /projects-presentation$\{segment}
            - ComposeFieldApi=projectId,/projects/core,ids,shallow,id,project
        - id: projectspresentation_route
          uri: ${configs.api.projects.presentationBaseURL}
          predicates:
            - Path=/projects/presentations/**
          filters:
            - RewritePath=/projects/presentations(?<segment>.*), /projects-presentation$\{segment}
        # MEDIA
        - id: media_route
          uri: ${configs.api.media.baseURL}
          predicates:
            - Path=/media/**
          filters:
            - RewritePath=/media(?<segment>.*), /$\{segment}

